# Server Configuration
server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://wnms13032104_db_user:YlRRP7uGnZGWOH9R@cluster0.huspz1t.mongodb.net/internship_task_tracker?retryWrites=true&w=majority


# JWT Configuration (We will use this in the Security phase)
app.jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3QgYXV0aGVudGljYXRpb24=
app.jwt.expiration-ms=86400000

# Logging (Helps us see what MongoDB is doing)
logging.level.org.springframework.data.mongodb.core=DEBUG